### ISSUE TITLE
Suggestion: add sweep function for potential stucked tokens

### ISSUE THREAD

**Issue by storming0x** [banteg/yearn-vesting-escrow#12]
This is from experience with current version of vesting contract. 

Some vested tokens could be accidentally claimed to same vesting contract and the lack of sweep function doesn't allow to recover them.

Also can be useful in case other tokens are sent to the contract accidentally.

This sweep can be called by the recipient of the vesting, since it should not have access to locked balance, only balanceOf of erc20 provided through argument address.

**Comment by banteg** [comment]
added in #9
