### ISSUE TITLE
rewrite to ape and update

### ISSUE THREAD

**Issue by banteg** [banteg/yearn-vesting-escrow#15]
assigned to @milkyklim

- [x] rewrite from brownie to ape
- [x] upgrade to latest vyper
- [x] add tests for newly merged features
- [ ] clean up contract
- [ ] identify other features to add/remove
- [x] use new vyper blueprints in the factory
- [ ] get a review from @banteg @fubuloubu and @storming0x
- [ ] deploy the new version

**Comment by fubuloubu** [comment]
You can upgrade Brownie to Ape without issue, but some ape features work best with newer versions of vyper

The vyper should probably be upgraded first, to 0.3.9 (or 0.3.10 when it come sout soon)
